ToshokanApp/src/ToshokanApp.Presentation/Controllers/BookController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using ToshokanApp.Core.Dtos;
using ToshokanApp.Core.Models;
using ToshokanApp.Core.Services;

namespace ToshokanApp.Presentation.Controllers;

public class BookController : Controller
{

    private readonly IConfiguration bookDirConfiguration;
    private readonly IBookService bookService;
    private readonly IIdentityService identityService;
    private readonly ICloudinaryService cloudinaryService;
    public BookController(IBookService bookService, IIdentityService identityService, IConfiguration bookDirConfiguration, ICloudinaryService cloudinaryService)
    {
        this.bookService = bookService;
        this.identityService = identityService;
        this.bookDirConfiguration = bookDirConfiguration;
        this.cloudinaryService = cloudinaryService;
    }

    [HttpGet]
    [AllowAnonymous]
    public async Task<IActionResult> Index()
    {
        base.HttpContext.Response.Cookies.Delete("CurrentBookId");
        var books = await this.bookService.GetAllAsync();
        return View(books);
    }

    [HttpGet]
    [ActionName("GetByName")]
    [AllowAnonymous]
    public async Task<IActionResult> GetByName(string? name)
    {
        var booksByName = await this.bookService.GetByNameAsync(name);
        return View("Index", booksByName);
    }

    [HttpGet]
    [ActionName("GetById")]
    [AllowAnonymous]
    public async Task<IActionResult> GetById(Guid id)
    {
        var bookById = await this.bookService.GetByIdAsync(id);
        var commentDtos = this.bookService.GetComments(bookById.Id);

        var bookComments = new BookComment
        {
            book = bookById,
            comments = commentDtos
        };

        Guid userId;
        var hashedSenderId = base.HttpContext.Request.Cookies["CurrentUserId"];

        if (string.IsNullOrWhiteSpace(hashedSenderId) == false)
        {
            Guid.TryParse(hashedSenderId, out userId);
            var user = await identityService.GetByIdAsync(userId);
            ViewBag.InPurchased = user.PurchasedBooks.Contains(id);
            ViewBag.InWishlist = user.WishList.Contains(id);
        }       
        else{
            ViewBag.InPurchased = false;
            ViewBag.InWishlist = false;
        }

        base.HttpContext.Response.Cookies.Append("CurrentBookId", bookById.Id.ToString());
        ViewBag.avatarDirPath = bookDirConfiguration["StaticFileRoutes:Avatars"];
        return View("Description", bookComments);
    }

    [HttpPost]
    [ActionName("Add")]
    [Route("api/[controller]/[action]/")]
    [Authorize("RequireAdminAccess")]
    public async Task<IActionResult> Add([FromForm] Book newBook, IFormFile layout, IFormFile bookFile)
    {
        try
        {
            newBook.Id = new Guid();
            newBook.AddedDate = DateTime.Now;

            string layoutUrl = "https://static.vecteezy.com/system/resources/previews/000/357/095/non_2x/vector-book-icon.jpg";
            string fileUrl = string.Empty;

            if (layout != null)
            {
                layoutUrl = await cloudinaryService.UploadImageAsync(layout, "book-layouts");
            }

            if (bookFile != null)
            {
                fileUrl = await cloudinaryService.UploadPdfAsync(bookFile, "book-files");
            }

            newBook.LayoutUrl = layoutUrl;
            newBook.FileUrl = fileUrl;

            await this.bookService.AddAsync(newBook);
        }
        catch (Exception ex)
        {
            TempData["error"] = ex.Message;
        }

        return base.RedirectToAction("Index");
    }



    [HttpGet]
    [ActionName("DownloadBook")]
    public async Task<IActionResult> DownloadBook(Guid id)
    {
        var book = await this.bookService.GetByIdAsync(id);
        
        if (string.IsNullOrEmpty(book.FileUrl))
        {
            return NotFound();
        }

        return Redirect(book.FileUrl);
    }


    [HttpGet]
    [ActionName("DeleteBook")]
    [Authorize("RequireAdminAccess")]
    public async Task<IActionResult> Delete(Guid id)
    {
        if (ModelState.IsValid)
        {
            await this.bookService.DeleteAsync(id);
            return base.RedirectToAction("Index");
        }

        return Forbid();
    }
}

ToshokanApp/src/ToshokanApp.Presentation/Controllers/CommentController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using ToshokanApp.Core.Models;
using ToshokanApp.Core.Services;

namespace ToshokanApp.Presentation.Controllers;

public class CommentController : Controller
{
    private readonly ICommentService commentService;
    public CommentController(ICommentService commentService, IDataProtectionProvider dataProtectionProvider)
    {
        this.commentService = commentService;
    }

    [HttpGet]
    [Route("[controller]")]
    public async Task<IActionResult> Index()
    {
        var comments = await this.commentService.GetAllAsync();

        return base.View(comments);
    }

    [HttpPost]
    [Route("api/[controller]")]
    public async Task<IActionResult> Add(Comment comment)
    {
        Guid senderId;
        var hashedSenderId = base.HttpContext.Request.Cookies["CurrentUserId"];

        if (string.IsNullOrWhiteSpace(hashedSenderId) == false)
        {

            if (Guid.TryParse(hashedSenderId, out senderId))
            {

                comment.SenderId = senderId;
            }
        }

        Guid bookId;
        var hashedBookId = base.HttpContext.Request.Cookies["CurrentBookId"];

        if (string.IsNullOrWhiteSpace(hashedBookId) == false)
        {

            if (Guid.TryParse(hashedBookId, out bookId))
            {
                comment.BookId = bookId;

            }
        }
        if (ModelState.IsValid)
        {
            await commentService.AddAsync(comment);
            return base.RedirectToAction("GetById", "Book", new
            {
                id = comment.BookId
            });
        }
        return Forbid();
    }

    [HttpGet]
    [ActionName("Delete")]
    [Route("api/[controller]")]
    public async Task<IActionResult> Delete(Guid commentId)
    {
        if (ModelState.IsValid)
        {
            var comment = await this.commentService.GetByIdAsync(commentId);

            if (comment != null)
            {
                var bookId = comment?.BookId;
                await this.commentService.DeleteAsync(commentId);
            }
            return base.RedirectToAction("GetById", "Book", new
            {
                id = comment.BookId
            });

        }

        return Forbid();
    }
}

ToshokanApp/src/ToshokanApp.Presentation/Controllers/IdentityController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using ToshokanApp.Core.Dtos;
using System.Security.Cryptography;
using ToshokanApp.Core.Services;
using System.Text;
using ToshokanApp.Core.Models;
using ToshokanApp.Infrastructure.Services;
using System.Net.Mail;
using System.Net;

namespace ToshokanApp.Infrastructure.Controllers;
public class IdentityController : Controller
{
    private readonly IIdentityService identityService;
    private readonly IBookService bookService;
    private readonly IEmailService emailService;
    private readonly IEmailTemplateService emailTemplateService;
    private readonly ICloudinaryService cloudinaryService;

    private readonly IConfiguration avatarDirConfiguration;

    private readonly IDataProtector dataProtector;
    public IdentityController(IIdentityService identityService, IDataProtectionProvider dataProtectionProvider, IConfiguration avatarDirConfiguration, IBookService bookService, IEmailService emailService, IEmailTemplateService emailTemplateService, ICloudinaryService cloudinaryService)
    {
        this.identityService = identityService;
        this.dataProtector = dataProtectionProvider.CreateProtector("identity");
        this.avatarDirConfiguration = avatarDirConfiguration;
        this.bookService = bookService;
        this.emailService = emailService;
        this.emailTemplateService = emailTemplateService;
        this.cloudinaryService = cloudinaryService;
    }

    [Route("/[controller]/[action]", Name = "LoginView")]
    [AllowAnonymous]
    public IActionResult Login(string? ReturnUrl)
    {
        var errorMessage = base.TempData["error"];
        ViewBag.ReturnUrl = ReturnUrl;
        if (errorMessage != null)
        {
            base.ModelState.AddModelError("All", errorMessage.ToString()!);
        }

        return base.View();
    }

    [HttpPost]
    [AllowAnonymous]
    [Route("/api/[controller]/[action]", Name = "LoginEndpoint")]
    public async Task<IActionResult> Login([FromForm] LoginDto loginDto)
    {
        loginDto.Password = Convert.ToBase64String(Encoding.UTF8.GetBytes(loginDto.Password));
        var foundUser = await this.identityService.Login(loginDto);
        if (foundUser == null)
        {
            base.TempData["error"] = "Incorrect login or password!";
            return base.RedirectToRoute("LoginView", new
            {
                loginDto.ReturnUrl
            });
        }
        var hashedUserId = this.dataProtector.Protect(foundUser.Id.ToString());

        var claims = new Claim[] {
                new(ClaimTypes.Email, foundUser.Email),
                new(ClaimTypes.Name, foundUser.Name),
                new("Id", hashedUserId),
                new(ClaimTypes.Role, await this.identityService.GetRole(foundUser.Id)),
            };

        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

        var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);

        await base.HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrincipal);

        if (string.IsNullOrWhiteSpace(loginDto.ReturnUrl) == false)
        {
            return base.Redirect(loginDto.ReturnUrl);
        }

        base.HttpContext.Response.Cookies.Append("CurrentUserId", foundUser.Id.ToString());
        return base.RedirectToAction(controllerName: "Book", actionName: "Index");
    }

    [HttpGet]
    [Authorize()]
    [Route("/api/[controller]/[action]", Name = "LogoutEndpoint")]
    public async Task<IActionResult> Logout(string? ReturnUrl)
    {

        base.HttpContext.Response.Cookies.Delete("CurrentUserId");
        await base.HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        return base.RedirectToRoute("LoginView", new
        {
            ReturnUrl
        });

    }

    [Route("/[controller]/[action]", Name = "RegistrationView")]
    [AllowAnonymous]
    public IActionResult Registration()
    {
        if (TempData["error"] != null)
        {
            ModelState.AddModelError("All", TempData["error"].ToString());
            System.Console.WriteLine(TempData["error"]);
        }

        return base.View();
    }

    [HttpPost]
    [AllowAnonymous]
    [Route("/api/[controller]/[action]", Name = "RegistrationEndpoint")]
    public async Task<IActionResult> Registration([FromForm] RegistrationDto registrationDto, IFormFile avatar)
    {
        try
        {
            registrationDto.Password = Convert.ToBase64String(Encoding.UTF8.GetBytes(registrationDto.Password));
            var userId = await this.identityService.Registration(registrationDto);
            if (userId == null) throw new Exception("This email is already being used by another user");

            string avatarUrl;
            if (avatar == null)
            {
                avatarUrl = "https://wallpapers.com/images/hd/blank-default-pfp-wue0zko1dfxs9z2c.jpg";
            }
            else
            {
                avatarUrl = await cloudinaryService.UploadImageAsync(avatar, "avatars");
            }

            if (userId.HasValue)
            {
                await identityService.UpdateAvatarUrlAsync(userId.Value, avatarUrl);
                
                try
                {
                    var userName = registrationDto.Name;
                    var welcomeMessage = emailTemplateService.GenerateWelcomeEmailTemplate(userName);
                    await emailService.SendEmailAsync(registrationDto.Email, "Welcome to Toshokan!", welcomeMessage);
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Welcome email failed: {ex.Message}");
                }
            }
        }
        catch (Exception ex)
        {
            TempData["error"] = ex.Message;
            return base.RedirectToRoute("RegistrationView");
        }

        return base.RedirectToRoute("LoginView");
    }


    [HttpPost]
    [Authorize()]
    [Route("/[controller]/[action]", Name = "BuyBookEndpoint")]
    public async Task<IActionResult> BuyBook(string? ReturnUrl)
    {
        try
        {
            Guid userId;
            var hashedSenderId = base.HttpContext.Request.Cookies["CurrentUserId"];
            Guid.TryParse(hashedSenderId, out userId);

            Guid bookId;
            var hashedBookId = base.HttpContext.Request.Cookies["CurrentBookId"];
            Guid.TryParse(hashedBookId, out bookId);
            await this.identityService.BuyBook(userId, bookId);
            return RedirectToAction("GetById", "Book", new { id = bookId });
        }
        catch (Exception ex)
        {
            TempData["error"] = ex.Message;
        }
        return base.RedirectToAction("Index", "Book");
    }


    [HttpPost]
    [Authorize()]
    [Route("/[controller]/[action]", Name = "AddtoWishlistBookEndpoint")]
    public async Task<IActionResult> AddtoWishlistBook(string? ReturnUrl)
    {
        try
        {
            Guid userId;
            var hashedSenderId = base.HttpContext.Request.Cookies["CurrentUserId"];
            Guid.TryParse(hashedSenderId, out userId);

            Guid bookId;
            var hashedBookId = base.HttpContext.Request.Cookies["CurrentBookId"];
            Guid.TryParse(hashedBookId, out bookId);
            await this.identityService.AddtoWishlistBook(userId, bookId);
            return RedirectToAction("GetById", "Book", new { id = bookId });
        }

        catch (Exception ex)
        {
            TempData["error"] = ex.Message;
        }
        return base.RedirectToAction("Index", "Book");
    }


    [HttpPost]
    [Authorize()]
    [Route("/[controller]/[action]", Name = "RemovefromWishlistBookEndpoint")]
    public async Task<IActionResult> RemovefromWishlistBook(string? ReturnUrl)
    {
        try
        {
            Guid userId;
            var hashedSenderId = base.HttpContext.Request.Cookies["CurrentUserId"];
            Guid.TryParse(hashedSenderId, out userId);

            Guid bookId;
            var hashedBookId = base.HttpContext.Request.Cookies["CurrentBookId"];
            Guid.TryParse(hashedBookId, out bookId);
            await this.identityService.RemovefromWishlistBook(userId, bookId);
            return RedirectToAction("GetById", "Book", new { id = bookId });
        }
        catch (Exception ex)
        {
            TempData["error"] = ex.Message;
            System.Console.WriteLine(TempData["error"]);
        }
        return base.RedirectToAction("Index", "Book");
    }


    [HttpGet]
    [AllowAnonymous]
    [Route("[controller]/[action]/{id}")]
    [ActionName("GetById")]
    public async Task<ActionResult> GetById(Guid id)
    {
        var user = await identityService.GetByIdAsync(id);
        Guid senderId;
        var hashedSenderId = base.HttpContext.Request.Cookies["CurrentUserId"];

        if (string.IsNullOrWhiteSpace(hashedSenderId) == false)
        {

            Guid.TryParse(hashedSenderId, out senderId);
            if (senderId == id)
            {
                ViewBag.IsCurrentAccount = true;
                ViewBag.HasPendingRequest = await identityService.HasPendingRequest(id);
            }
            else ViewBag.IsCurrentAccount = false;
        }
        else
        {
            ViewBag.IsCurrentAccount = false;
        }
        ViewBag.AvatarUrl = user.AvatarUrl ?? "https://wallpapers.com/images/hd/blank-default-pfp-wue0zko1dfxs9z2c.jpg";
        ViewBag.UserId = user.Id;

        List<Book> purchasedBooks = new List<Book>();
        foreach (var bookId in user.PurchasedBooks)
        {
            purchasedBooks.Add(await this.bookService.GetByIdAsync(bookId));
        }
        List<Book> wishList = new List<Book>();

ToshokanApp/src/ToshokanApp.Presentation/Views/Book/Description.cshtml
@model BookComment

<link rel="stylesheet" href="~/wwwroot/css/styles.css">

@{
    ViewData["Title"] = "Description";

    var hasAccess = User.Claims.Any(c => c.Type == ClaimTypes.Role && c.Value == "Admin");


    var bookName = Model.book.Name;

    var comment = new Comment();
}

<div class="container mt-5">
    <h2>@bookName</h2>

    <div class="card">
        <img src="@(Model.book.LayoutUrl ?? "https://static.vecteezy.com/system/resources/previews/000/357/095/non_2x/vector-book-icon.jpg")" class="card-img-top" alt="@Model.book.Name" style="max-width: 300px; margin: 20px auto; display: block;">
        <div class="card-body">
        <div class="card-body">
            <p class="card-text"><strong>Name:</strong> @(Model?.book.Name ?? "UNKNOWN")</p>
            <strong>Author:<a target="_blank" href="https://en.wikipedia.org/w/index.php?search=@(Model?.book.Author)&title=Special%3ASearch&ns0=1" class="card-text">@(Model?.book.Author ?? "UNKNOWN")</a></strong>
            <p class="card-text"><strong>Year:</strong> @(Model?.book.PublicationYear?.ToString() ?? "UNKNOWN")</p>
            <p class="card-text"><strong>Genre:</strong> @(Model?.book.Genre ?? "UNKNOWN")</p>
            <p class="card-text"><strong>Language:</strong> @(Model?.book.Language ?? "UNKNOWN")</p>
            <p class="card-text"><strong>Description:</strong> @(Model?.book.Description ?? "UNKNOWN")</p>
        </div>
        @if (ViewBag.InPurchased && base.User.Identity?.IsAuthenticated)
        {
            <div>
            <a id="downloadButton" href="@Url.Action("DownloadBook", "Book", new { id = Model?.book.Id})"
                class="btn btn-primary">Download File</a>
            </div>
        }
        else
        {
            <div>
                @using (Html.BeginForm("BuyBook", "Identity", FormMethod.Post, new { id = Model?.book.Id }))
                {
                    <button type="submit" class="btn btn-primary" id="buyButton">Buy</button>
                    <div class="alert alert-warning mt-3" role="alert" id="buyAlert" style="display: none;">
                        Please log in to buy the book.
                    </div>
                }
            </div>
        }

        @if (ViewBag.InWishlist && base.User.Identity?.IsAuthenticated)
        {

            <div>
                @using (Html.BeginForm("RemoveFromWishlistBook", "Identity", FormMethod.Post, new { id = Model?.book.Id }))
                {
                    <button type="submit" class="btn btn-primary" id="removeWishlistButton">Remove from Wishlist</button>
                    <div class="alert alert-warning mt-3" role="alert" id="removeWishlistAlert" style="display: none;">
                        Please log in to add the book to your wishlist.
                    </div>
                }
            </div>
        }
        else
        {
            <div>
                @using (Html.BeginForm("AddToWishlistBook", "Identity", FormMethod.Post, new { id = Model?.book.Id }))
                {
                    <button type="submit" class="btn btn-primary" id="addWishlistButton">Add to Wishlist</button>
                    <div class="alert alert-warning mt-3" role="alert" id="addWishlistAlert" style="display: none;">
                        Please log in to add the book to your wishlist.
                    </div>
                }
            </div>
        }
    </div>

    <hr>

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Comments</h5>

            @foreach (var item in Model.comments)
            {
                <div class="media mb-3">

                    @* <a href="@Url.Action("GetById", "Identity", new { id = item.SenderId})" class="btn"> *@
                        @* <img src="~/Avatars/@(item.SenderId).jpg" class="mr-3 rounded-circle" alt="User Avatar" style="width: 64px;"> *@
                    @* </a> *@
                    <div class="media-body">
                        <a href="@Url.Action("GetById", "Identity", new { id = item.SenderId})" class="btn"><h6 class="mt-0">@item.SenderName @item.SenderSurname</h6></a>
                        <p>@item.Text</p>
                        @if(hasAccess){
                            <a href="@Url.Action("Delete", "Comment", new { commentId = item.Id })" class="btn btn-primary mt-auto">X</a>
                        }
                    </div>
                </div>
            }

            <form asp-controller="Comment" asp-action="Add" method="post" id="commentForm">
                <div class="form-group">
                    <label asp-for="@comment.Text" class="control-label">Comment</label>
                    <input asp-for="@comment.Text" class="form-control" id="commentInput" />
                    <span asp-validation-for="@comment.Text" class="text-danger"></span>
                </div>
                <div class="form-group">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <button type="submit" class="btn btn-primary" id="addButton">Add</button>
                    }
                    else
                    {
                        <button type="button" class="btn btn-primary" id="addButton" disabled>Add</button>
                        <div class="alert alert-warning mt-3" role="alert" id="loginAlert" style="display: none;">
                            Please log in to add a comment.
                        </div>
                    }
                </div>
            </form>
            @section Scripts {
                <script>
                    $(document).ready(function () {
                        $('#addButton').click(function (e) {
                            if (!@User.Identity.IsAuthenticated.ToString().ToLower()) {
                                e.preventDefault();
                                $('#loginAlert').slideDown();
                                setTimeout(function () {
                                    $('#loginAlert').slideUp();
                                }, 3000);
                            }
                        });

                        $('#commentInput').on('keyup change', function () {
                            validateForm();
                        });

                        function validateForm() {
                            var isValid = true;
                            $('#commentForm input[type="text"]').each(function () {
                                if ($(this).val() === '') {
                                    isValid = false;
                                }
                            });

                            $('#addButton').prop('disabled', !isValid);
                        }

                        $('#buyBookForm').submit(function (e) {
                            if (!@User.Identity.IsAuthenticated.ToString().ToLower()) {
                                e.preventDefault();
                                $('#buyAlert').slideDown();
                                setTimeout(function () {
                                    $('#buyAlert').slideUp();
                                }, 3000);
                            }
                        });

                        $('#addWishlistForm').submit(function (e) {
                            if (!@User.Identity.IsAuthenticated.ToString().ToLower()) {
                                e.preventDefault();
                                $('#addWishlistAlert').slideDown();
                                setTimeout(function () {
                                    $('#addWishlistAlert').slideUp();
                                }, 3000);
                            }
                        });

                        $('#removeWishlistForm').submit(function (e) {
                            if (!@User.Identity.IsAuthenticated.ToString().ToLower()) {
                                e.preventDefault();
                                $('#removeWishlistAlert').slideDown();
                                setTimeout(function () {
                                    $('#removeWishlistAlert').slideUp();
                                }, 3000);
                            }
                        });
                        validateForm();
                    });
                </script>
            }

        </div>
    </div>
</div>